name: Continuous Integration

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-unittests-build:
    name: Lint, Unit Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Use Correct Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
